name: "Test the repos workflow"

on:
  push:
    branches:
      - main


jobs:
  test-repo:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repos"
        uses: actions/checkout@v4

      - name: "Curl installation"
        run: apk --no-cache add curl

      - name: "Script checking"
        run: ./check.sh 
